version: '3'

services:

  app-node:
    build:
      context: ../../node
    container_name: app-node
    networks:
      - node-network
    volumes:
      - ../../node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"

  mysql-database:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql-database
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    volumes:
      - mysql-volume:/var/lib/mysql


networks:
  node-network:
    driver: bridge

volumes:
  mysql-volume: